{"timestamp":"2025-09-08T10:26:29.511357","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-08T10:26:29.512135","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-08T10:26:31.215932Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T10:26:31.225408Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T10:26:31.232435Z","level":"info","event":"Current task name:prepare_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T10:26:31.241024Z","level":"info","event":"Dag name:ml_pipeline_demo","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T10:26:31.243977Z","level":"info","event":"---- Inside prepare_data component ----","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T10:26:31.612015","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OSError","exc_value":"Cannot save file into a non-existent directory: '/opt/airflow/data'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/ml_pipeline.py","lineno":17,"name":"prepare_data"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py","lineno":3902,"name":"to_csv"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py","lineno":1152,"name":"to_csv"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py","lineno":247,"name":"save"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py","lineno":739,"name":"get_handle"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py","lineno":604,"name":"check_parent_directory"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-08T10:26:31.615097Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T10:26:31.617790Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T10:26:31.618910Z","level":"info","event":"Task:<Task(PythonOperator): prepare_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T10:26:31.620187Z","level":"info","event":"Failure caused by Cannot save file into a non-existent directory: '/opt/airflow/data'","chan":"stdout","logger":"task"}
